---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(mgnet)
```

```{r, message=FALSE}
mOTU <- readRDS("../data/R/mOTU.rds") %>%
  filter_taxa(sum(abun) != 0)
amr <- readRDS("../data/R/amr.rds") %>%
  filter_taxa(sum(abun) != 0)
mOTU_old <- readRDS("../data/R/mOTU_old.rds")
```

## Filtering mOTU

```{r}
mOTU <- mOTU %>%
  mutate_taxa(
    m_prevalence = sum(abun>0)  / length(abun),
    m_log10_sum_taxa = log10(sum(abun)),
    m_log10_max_rel = log10(max(rela)),
    m_log10_mean_no_zero = log10(mean(abun[abun>0])),
    m_log10_median_no_zero = log10(median(abun[abun>0]))) 
```

```{r, fig.width=8, fig.height=4}
mOTU %>%
  gather_taxa() %>%
  select(taxa_id, starts_with("m_")) %>%
  pivot_longer(-taxa_id, names_to = "measurments", values_to = "values") %>%
  ggplot(aes(x = values)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "darkblue") +
  facet_wrap(~measurments, scales = "free", ncol = 3) +
  theme_bw()
```

```{r}
mOTU_filt <- mOTU %>%
  mutate_meta(sample_sum = sum(abun)) %>%
  filter_taxa(m_prevalence >= .25 & m_log10_median_no_zero >= 0) %>%
  mutate_meta(preserved_counts = sum(abun) / sample_sum) 
```

```{r, fig.width=5, fig.height=3}
mOTU_filt %>%
  gather_meta() %>%
  ggplot(aes(x = preserved_counts)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "darkblue") + 
  theme_bw()
```

```{r}
mOTU_filt <- mOTU_filt %>%
  filter_meta(preserved_counts >= .9)
```

## Comparison with the OLD mOTUs

```{r}
mOTU_old <- mOTU_old %>%
  mutate_taxa(
    m_prevalence = sum(abun>0) / length(abun),
    m_log10_sum_taxa = log10(sum(abun)),
    m_log10_max_rel = log10(max(rela)),
    m_log10_median_no_zero = log10(median(abun[abun>0])),
    m_log10_mean_no_zero = log10(mean(abun[abun>0]))) 
```

```{r, fig.width=8, fig.height=4}
mOTU_old %>%
  gather_taxa() %>%
  select(taxa_id, starts_with("m_")) %>%
  pivot_longer(-taxa_id, names_to = "measurments", values_to = "values") %>%
  ggplot(aes(x = values)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "darkblue") +
  facet_wrap(~measurments, scales = "free", ncol = 3) +
  theme_bw()
```

### Compare Prevalence and Prevalence sample sums

```{r}
print("mOTU_new")
pull_taxa(mOTU, m_prevalence) %>% quantile(seq(0,1,.1)) %>% 
  format(scientific = TRUE, digits = 3)

print("mOTU_old")
pull_taxa(mOTU_old, m_prevalence) %>% quantile(seq(0,1,.1)) %>% 
  format(scientific = TRUE, digits = 3)
```

```{r}
print("mOTU_new")
rowSums(abun(mOTU)) %>% quantile(seq(0,1,.1))

print("mOTU_old")
rowSums(abun(mOTU_old)) %>% quantile(seq(0,1,.1))
```

## Filtering amr


```{r}
rowSums(abun(amr)) %>% quantile(seq(0,1,.1)) %>% round(2)
```

```{r}
filter_meta(amr, sum(abun) < 15) %>%
  gather_meta() %>%
  group_by(Region) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
```


```{r, fig.width=8, fig.height=4}
amr %>%
  mutate_meta(sample_sum = sum(abun)) %>%
  gather_meta() %>%
  ggplot(aes(x = sample_sum, fill = Region)) +
  geom_histogram(bins = 30, color = "black") +
  theme_bw() +
  theme(legend.position = "right") +
  scale_x_log10()
```


```{r}
amr_filt <- amr %>%
  filter_meta(sum(abun) >= 15)
```

```{r}
amr_filt <- amr_filt %>%
  mutate_taxa(
    m_prevalence = sum(abun>0) / length(abun),
    m_log10_sum_taxa = log10(sum(abun)),
    m_log10_max_rel = log10(max(rela)),
    m_log10_mean_no_zero = log10(mean(abun[abun>0])),
    m_log10_median_no_zero = log10(median(abun[abun>0]))) 
```

```{r, fig.width=8, fig.height=4}
amr_filt %>%
  gather_taxa() %>%
  select(taxa_id, starts_with("m_")) %>%
  pivot_longer(-taxa_id, names_to = "measurments", values_to = "values") %>%
  ggplot(aes(x = values)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "darkblue") +
  facet_wrap(~measurments, scales = "free", ncol = 3) +
  theme_bw()
```

```{r}
amr_filt <- amr_filt %>%
  mutate_meta(sample_sum = sum(abun)) %>%
  filter_taxa(m_prevalence >= .25 & m_log10_median_no_zero >= -2) %>%
  mutate_meta(preserved_counts = sum(abun) / sample_sum) 
```

```{r, fig.width=5, fig.height=3}
amr_filt %>%
  gather_meta() %>%
  ggplot(aes(x = preserved_counts)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "darkblue") + 
  theme_bw()
```

```{r}
amr_filt <- amr_filt %>%
  filter_meta(preserved_counts >= .8)
```

### Get Only the filtered samples for both

```{r}
preserved_samples <- intersect(sample_id(mOTU_filt), sample_id(amr_filt))
```

```{r, fig.width=12}
# How are the removed samples???
mOTU %>%
  gather_meta() %>%
  filter(!sample_id %in% preserved_samples) %>%
  group_by(Region, country_alt) %>%
  summarise(n = n(), .groups = "drop") %>%
  ggplot(aes(x = country_alt, y = n, fill = Region)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  theme(legend.position = "top")
```





```{r}
mOTU_filt <- set_norm_CLR(mOTU_filt[preserved_samples, ])
amr_filt <- set_norm_CLR(amr_filt[preserved_samples, ])
```


## Construct the network mOTU + amr (all acquired and functional)

```{r}
mOTU_amr_netw <- mgnet(
  norm = cbind(norm(mOTU_filt), norm(amr_filt)),
  meta = meta(mOTU_filt) %>% select(-preserved_counts),
  taxa = bind_rows(taxa(mOTU_filt), taxa(amr_filt))
)
```

```{r}
spearman_mat <- cor(norm(mOTU_amr_netw), method = "spearman") %>%
  as_tibble(rownames = "taxa_i") %>%
  pivot_longer(-taxa_i, names_to = "taxa_j", values_to = "spearman") %>%
  filter(taxa_i > taxa_j)
```

```{r, fig.width=4, fig.height=3, warning=FALSE}
spearman_mat %>%
  ggplot(aes(x = spearman)) +
  geom_histogram(binwidth = .05, fill = "lightblue", color = "darkblue") +
  theme_bw() +
  xlim(-1.05, 1.05) 
```


```{r}
mOTU_amr_netw <- mOTU_amr_netw %>%
  constructCorrCLRNet(
    cor_method = "spearman",
    thresh_method = "absolute", 
    thresh_value = 0.5) %>%
  cluster_signed()
```

```{r}
comm_sizes <- igraph::sizes(comm(mOTU_amr_netw))
comm_sizes[comm_sizes>1]
```


## Draw Network

```{r}
mOTU_amr_netw_filt <- mOTU_amr_netw %>%
  filter_taxa(n() > 10, .by = "comm_id")
```

```{r}
mOTU_amr_netw_filt <- mOTU_amr_netw_filt %>%
  mutate_taxa(family_fct = if_else(is.na(family_ncbi), "Unknown", family_ncbi)) %>%
  mutate_taxa(family_fct = fct_lump_n(family_fct, 30), .by = "") %>%
  colorize_taxa(family_fct, color_to = "color_family") %>% 
  mutate_taxa(class_amr_fct = factor(class_amr)) %>% 
  mutate_taxa(class_amr_fct = fct_lump_n(class_amr_fct, 20, other_level = "['other']"), .by = "") %>%
  colorize_taxa(class_amr_fct, color_to = "color_class_amr") %>%
  mutate_taxa(color_nodes = if_else(source == "mOTU", color_family, color_class_amr),
              color_nodes = if_else(source == "mOTU", 
                                    adjustcolor(color_family, alpha.f = .85),
                                    color_class_amr)) %>%
  mutate_taxa(vertex.frame.color = case_when(
    type == "mOTU" ~ "#838B83",
    type == "acquired" ~ "#8B0000",
    type == "functional" ~ "#008B45"
  )) %>%
  bind_taxa("degree_inta_pos"=degree_mgnet(mOTU_amr_netw_filt, "positive", "intra"),
            "degree" = degree(netw(mOTU_amr_netw_filt))) %>%
  mutate_taxa(comm_id_fct = factor(comm_id)) %>%
  colorize_taxa(comm_id_fct, color_to = "color_comm") %>%
  mutate_taxa(vertex_color_gut = case_when(
    is_from_gut ~ "brown",
    TRUE ~ "lemonchiffon"
  ))

color_family <- gather_taxa(mOTU_amr_netw_filt) %>%
  select(family_fct, color_family) %>%
  distinct() %>%
  deframe() 

color_amr <- gather_taxa(mOTU_amr_netw_filt) %>%
  select(class_amr_fct, color_class_amr) %>%
  filter(!is.na(class_amr_fct)) %>%
  distinct() %>%
  deframe()
names(color_amr) <- names(color_amr) %>%
  str_remove_all("\\[") %>% str_remove_all("\\]") %>% str_remove_all("'") 

color_comm <- gather_taxa(mOTU_amr_netw_filt) %>%
  select(comm_id_fct, color_comm) %>%
  filter(!is.na(comm_id_fct)) %>%
  distinct() %>%
  deframe()
color_comm <- color_comm[as.character(1:6)]
```

```{r}
#################################################################
# generic star vertex shape, with a parameter for number of rays
mystar <- function(coords, v=NULL, params) {
  vertex.color <- params("vertex", "color")
  if (length(vertex.color) != 1 && !is.null(v)) {
    vertex.color <- vertex.color[v]
  }
  vertex.size  <- 1/200 * params("vertex", "size")
  if (length(vertex.size) != 1 && !is.null(v)) {
    vertex.size <- vertex.size[v]
  }
  vertex.frame.color <- params("vertex", "frame.color")
  if (length(vertex.frame.color) != 1 && !is.null(v)) {
    vertex.frame.color <- vertex.frame.color[v]
  }
  vertex.frame.width <- params("vertex", "frame.width")
  if (length(vertex.frame.width) != 1 && !is.null(v)) {
    vertex.frame.width <- vertex.frame.width[v]
  }
  norays <- params("vertex", "norays")
  if (length(norays) != 1 && !is.null(v)) {
    norays <- norays[v]
  }

  mapply(coords[,1], coords[,2], vertex.color, 
         vertex.frame.color, vertex.frame.width,
         vertex.size, norays,
         FUN=function(x, y, bg, fg, lwd, size, nor) {
           symbols(x=x, y=y, bg=bg, fg=fg, lwd=lwd,
                   stars=matrix(c(size,size/2), nrow=1, ncol=nor*2),
                   add=TRUE, inches=FALSE)
         })
}
# no clipping, edges will be below the vertices anyway
add_shape("star", clip=shape_noclip,
                 plot=mystar, parameters=list(vertex.norays=5))
```

```{r, fig.width=18, fig.height=14}
png(filename = "network_taxonomy.png", width = 5400, height = 4200, res = 300)
x <- mOTU_amr_netw_filt %>%
   filter_taxa(degree >= 2)

set.seed(42)
layout_x <- layout_signed(netw(x), layout = with_fr(start.temp = .1))

layout(matrix(c(1,2), ncol=2), widths = c(1,.285))

par(mar=c(0,0,0,0))
plot(x,
     layout = layout_x,
     vertex.label = NA,
     posCol = rgb(0, 0, 1, .2), negCol = rgb(1, 0, 0, .2),
     widthFactor = .75,
     vertex.shape = if_else(pull_taxa(x,source) == "mOTU", "circle", "star"),
     vertex.size = colMeans(norm(x)),
     maxSize = 6, expFactor = 0.5, sumConst = 1,
     vertex.color = pull_taxa(x, color_nodes),
     vertex.frame.color = pull_taxa(x, vertex.frame.color),
     vertex.frame.width = if_else(pull_taxa(x,source) == "mOTU", .5, 2))

plot.new()
par(mar=c(0,0,0,0))

legend(x = 0, y = 1, xjust = 0,
       legend = tolower(names(color_family)), fill = color_family, title = "mOTU family", 
       ncol = 1, bty = "n", cex = 1.1, title.adj = 0)
legend(x = 0, y = .44, xjust = 0,
       legend = names(color_amr), fill = color_amr, title = "AMR class", 
       ncol = 1, bty = "n", title.adj = 0)
legend(
  x = 0, y = .07, xjust = 0, cex = 1.1,
  legend = c("mOTU","acquired","functional"),
  pch = c(1,11,11),
  col = c("#838B83", "#8B0000", "#008B45"),
  pt.cex = 2, bty = "n",
  title = "Source", horiz = T,
  lwd = 2, title.adj = 0
)

legend(
  x = 0, y = 0.015, xjust = 0, cex = 1.1,
  legend = c("Positive", "Negative"),
  lty = c(1, 1),       
  col = c("blue", "red"),  
  lwd = 2,             
  bty = "n",           
  horiz = TRUE,
  title = "Link Weights", title.adj = 0
)
dev.off()
```

```{r, fig.width=4, fig.height=8}
df <- gather_taxa(mOTU_amr_netw_filt) %>%
  mutate(who = case_when(
    type == "acquired" ~ "amr acquired",
    type == "functional" ~ "amr functional",
    comm_id == "4" & species_uhgg == "Klebsiella grimontii" & is_from_gut == TRUE ~ "human enterobacteriaceae",
    is_from_gut ~ "human",
    family_ncbi == "Enterobacteriaceae" ~ "enterobacteriaceae",
    family_ncbi == "Pseudomonadaceae" ~ "pseudomonadaceae",
    is.na(family_ncbi) ~ "unknown",
    TRUE ~ "other"
  )) %>%
  mutate(who = factor(who, levels = c("amr acquired", "amr functional","human", "human enterobacteriaceae", 
                                      "enterobacteriaceae", "pseudomonadaceae",
                                      "other", "unknown"))) %>%
  group_by(comm_id, who, color_comm) %>%
  summarise(n = n(), .groups = "drop") 

p_bar <- df %>%
  mutate(comm_id = factor(comm_id, levels = as.character(7:1))) %>%
  ggplot(aes(y = comm_id, x = n, fill = who)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  scale_fill_manual(values = c("amr acquired" = "#8B0000", "amr functional" = "#008B45",
                               "human" = "#CD6839", "unknown" = "#E3D6CBFF",
                               "human enterobacteriaceae" = "black",
                               "pseudomonadaceae" = "#B3BEE2FF", "enterobacteriaceae" = "#7089C6FF",
                               "other" = "#FFFACD")) +
  theme(axis.title.x = element_blank()) +
  labs(fill = "Source") +
  ylab("Communities") +
  theme(legend.position = "top") +
  guides(fill = guide_legend(ncol = 1, direction = "vertical")) +
  theme(axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 14)) +
  theme(
    axis.text = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    legend.text = element_text(size = 14),       # Increase legend text size
    legend.title = element_text(size = 16),      # Increase legend title size
    legend.key.size = unit(1.5, "lines")         # Increase legend key size
  )
```



```{r, fig.width=14, fig.height=14}
png(filename = "network_community.png", width = 4200, height = 4200, res = 300)
x <- mOTU_amr_netw_filt %>%
  filter_taxa(degree >= 2)

set.seed(42)
layout_x <- layout_signed(netw(x), layout = with_fr(start.temp = .1))

par(mar=c(0,0,0,0))
plot(x,
     layout = layout_x,
     vertex.label = NA,
     posCol = rgb(0, 0, 1, .2), negCol = rgb(1, 0, 0, .2),
     widthFactor = .75,
     vertex.shape = if_else(pull_taxa(x,source) == "mOTU", "circle", "star"),
     vertex.size = colMeans(norm(x)),
     maxSize = 6, expFactor = 0.5, sumConst = 1,
     vertex.frame.width = 3,
     vertex.color = if_else(pull_taxa(x,is_from_gut), "#CD6839", "#FFFACD"),
     vertex.frame.color = pull_taxa(x, color_comm))

legend(
  x = 1, y = -1, xjust = 1,
  legend = names(color_comm),
  col = color_comm,
  pch = 1, cex = 1.1,
  pt.cex = 2.5, bty = "n", lwd = 3,
  title = "Communities", horiz = T
)

legend(
  x = -1, y = -1, xjust = 0,
  legend = c("Human mOTU", "Other mOTU", "amr"),
  col = c("#CD6839", "#FFFACD", "black"),
  pch = c(19,19,11), cex = 1.1,
  pt.cex = 2.5, bty = "n",
  title = "Source", horiz = T
)
dev.off()
```

```{r}
library(ggpubr)
library(ggplot2)
library(grid)
library(png)

base_plot_grob <- rasterGrob(readPNG("network_community.png"), interpolate = TRUE)
```


```{r, fig.width=4, fig.height=14}
# Arrange the plots together using ggpubr
p_bar_fill <- ggarrange(
  ggplot() + theme_void(),
  p_bar,
  ggplot() + theme_void(),
  labels = c("", "B", ""),
  ncol = 1, heights = c(3/14, 8/14, 3/14), font.label = list(size = 24)
)
p_bar_fill
```



```{r, fig.width=18, fig.height=14}
combined_plot <- ggarrange(
  as_ggplot(base_plot_grob),
  p_bar_fill, 
  labels = c("A", ""),
  widths = c(14/18, 4/18),
  label.x = c(.1,0), label.y = c(.9,1), font.label = list(size = 24)
)
combined_plot
```


```{r}
png(filename = "networks_communities.png", width = 5400, height = 4200, res = 300)
combined_plot
dev.off()
```


## Filtering Measurments

```{r}

```


