---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(mgnet)
```

```{r}
gs <- readRDS("../data/R/global-sewage-mOTUs-amr.rds")
```

```{r}
gs %>%
  gather_meta() %>%
  group_by(city) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
```

```{r}
CPH <- gs %>%
  filter_meta(city == "Copenhagen") %>%
  split_taxa(source) %>%
  filter_taxa(sum(abun) > 0)

CPH <- CPH %>%
  mutate_taxa(
    prevalence = sum(abun>0)/length(abun),
    log10_sum_taxa = log10(sum(abun)),
    log10_max_rel = log10(max(rela)),
    .by = "taxa_id")

CPH %>%
  gather_taxa() %>%
  select(taxa_id, source, prevalence, log10_sum_taxa, log10_max_rel) %>%
  pivot_longer(-c(taxa_id, source), names_to = "measurements", values_to = "values") %>%
  ggplot(aes(x = values, fill = measurements)) +
  geom_histogram(bins = 40) +
  facet_wrap(~ source + measurements, scales = "free") +
  theme_bw() +
  theme(legend.position = "top")
```

```{r}
CPH <- CPH %>%
  mutate_meta(sum_sample_origin = sum(abun)) %>%
  mutate_taxa(
    prevalence_pass = prevalence >= .33,
    sum_taxa_pass = case_when(source == "mOTU" ~ log10_sum_taxa >= 1,
                              source == "amr" ~ log10_sum_taxa >= -2),
    max_rel_pass = case_when(source == "mOTU" ~ log10_max_rel >= -2,
                             source == "amr" ~ log10_max_rel >= -5)) %>%
  filter_taxa(prevalence_pass & sum_taxa_pass | max_rel_pass) %>%
  mutate_meta(lost_count = sum(abun) / sum_sample_origin)

CPH %>%
  gather_meta() %>%
  ggplot(aes(x = lost_count)) +
  geom_histogram(bins = 30)
```

```{r}
CPH <- CPH %>%
  set_norm_CLR()
```

```{r}
merge_mgnet <- function(x, y){
  mgnet(norm = cbind(norm(x), norm(y)),
        meta = meta(x),
        taxa = bind_rows(taxa(x), taxa(y)))
}

CPH_netw <- mgnetList(
  "mOTU-ResFinder" = merge_mgnet(CPH$mOTU,
                                 filter_taxa(CPH$amr, amr_group == "Resfinder")),
  "mOTU-Functional" = merge_mgnet(CPH$mOTU,
                                  filter_taxa(CPH$amr, amr_group == "Functional"))
) %>%
  constructCorrCLRNet(cor_method = "spearman",
                      thresh_method = "absolute", thresh_value = .8, cores = 6) %>%
  cluster_signed(cores = 6)
```

```{r}
CPH_netw_filt <- CPH_netw %>%
  filter_taxa(n() > 1, .by = c("mgnet", "comm_id"))

map(comm(CPH_netw_filt), sizes)

CPH_netw_filt <- CPH_netw %>%
  filter_taxa(n() > 10, .by = c("mgnet", "comm_id"))
```

```{r}
colormap_families  <- pull_taxa(CPH_netw_filt, "family") %>%
  unlist() %>% table %>% sort(decreasing = T) %>% names %>%
  colormap_categories(distinct_colors = 40)
colormap_families <- setNames(adjustcolor(colormap_families, .95), names(colormap_families))

colormap_class_amr <- pull_taxa(CPH_netw_filt, amr_class) %>%
  unlist() %>% table %>% sort(decreasing = T) %>% names %>%
  colormap_categories()

colormap_comms <- colormap_communities(comm(CPH_netw_filt))

CPH_netw_filt <- CPH_netw_filt %>%
  mutate_taxa(vertex_color_family_classAMR = case_when(
    source == "mOTU" ~ colormap_families[family],
    source == "amr" ~ colormap_class_amr[amr_class],
  )) 
```

```{r}
#################################################################
# generic star vertex shape, with a parameter for number of rays
mystar <- function(coords, v=NULL, params) {
  vertex.color <- params("vertex", "color")
  if (length(vertex.color) != 1 && !is.null(v)) {
    vertex.color <- vertex.color[v]
  }
  vertex.size  <- 1/200 * params("vertex", "size")
  if (length(vertex.size) != 1 && !is.null(v)) {
    vertex.size <- vertex.size[v]
  }
  vertex.frame.color <- params("vertex", "frame.color")
  if (length(vertex.frame.color) != 1 && !is.null(v)) {
    vertex.frame.color <- vertex.frame.color[v]
  }
  vertex.frame.width <- params("vertex", "frame.width")
  if (length(vertex.frame.width) != 1 && !is.null(v)) {
    vertex.frame.width <- vertex.frame.width[v]
  }
  norays <- params("vertex", "norays")
  if (length(norays) != 1 && !is.null(v)) {
    norays <- norays[v]
  }

  mapply(coords[,1], coords[,2], vertex.color, 
         vertex.frame.color, vertex.frame.width,
         vertex.size, norays,
         FUN=function(x, y, bg, fg, lwd, size, nor) {
           symbols(x=x, y=y, bg=bg, fg=fg, lwd=lwd,
                   stars=matrix(c(size,size/2), nrow=1, ncol=nor*2),
                   add=TRUE, inches=FALSE)
         })
}
# no clipping, edges will be below the vertices anyway
add_shape("star", clip=shape_noclip,
                 plot=mystar, parameters=list(vertex.norays=5))
```

```{r, fig.width=12, fig.height=14}
layout(mat = matrix(c(1,2,3,3,4,5), ncol = 2, byrow = T), heights = c(1,.2,1))

x <- CPH_netw_filt$`mOTU-ResFinder`
set.seed(42)
layout_x <- layout_with_fr(subgraph.edges(netw(x), which(E(netw(x))$weight>0)), 
                           start.temp = 10)
par(mar=c(0,0,0,0))
plot(x,
     layout = layout_x,
     vertex.label = NA,
     posCol = rgb(0, 0, 1, .5), negCol = rgb(1, 0, 0, .5),
     vertex.shape = ifelse(taxa(x)$source == "mOTU", "circle", "star"),
     vertex.size = colMeans(norm(x)) + 3,
     vertex.color = pull_taxa(x, "vertex_color_family_classAMR"))
mtext("a", side = 3, line = -4, adj = 0.1, cex = 2) 



x <- CPH_netw_filt$`mOTU-Functional`
set.seed(42)
layout_x <- layout_with_fr(subgraph.edges(netw(x), which(E(netw(x))$weight>0)), 
                           start.temp = 5)
par(mar=c(0,0,0,0))
plot(x,
     layout = layout_x,
     vertex.label = NA,
     posCol = rgb(0, 0, 1, .5), negCol = rgb(1, 0, 0, .5),
     vertex.shape = ifelse(taxa(x)$source == "mOTU", "circle", "star"),
     vertex.size = colMeans(norm(x)) + 3,
     vertex.color = pull_taxa(x, "vertex_color_family_classAMR"))
mtext("b", side = 3, line = -4, adj = 0.1, cex = 2) 

plot.new()
legend("center",
       legend = names(colormap_families)[1:40], fill = colormap_families[1:40],
       ncol = 7)

x <- CPH_netw_filt$`mOTU-ResFinder`
set.seed(42)
layout_x <- layout_with_fr(subgraph.edges(netw(x), which(E(netw(x))$weight>0)), 
                           start.temp = 10)
par(mar=c(0,0,0,0))
plot(x,
     layout = layout_x,
     vertex.label = NA,
     posCol = rgb(0, 0, 1, .5), negCol = rgb(1, 0, 0, .5),
     vertex.shape = ifelse(taxa(x)$source == "mOTU", "circle", "star"),
     vertex.size = colMeans(norm(x)) + 3,
     vertex.color = if_else(pull_taxa(x,is_from_gut), "brown", "lemonchiffon"),
     vertex.frame.color = colormap_comms$`mOTU-ResFinder`[comm_id(x)],
     vertex.frame.width = 2.5)
mtext("a", side = 3, line = -4, adj = 0.1, cex = 2) 

x <- CPH_netw_filt$`mOTU-Functional`
set.seed(42)
layout_x <- layout_with_fr(subgraph.edges(netw(x), which(E(netw(x))$weight>0)), 
                           start.temp = 5)
par(mar=c(0,0,0,0))
plot(x,
     layout = layout_x,
     vertex.label = NA,
     posCol = rgb(0, 0, 1, .5), negCol = rgb(1, 0, 0, .5),
     vertex.shape = ifelse(taxa(x)$source == "mOTU", "circle", "star"),
     vertex.size = colMeans(norm(x)) + 3,
     vertex.color = if_else(pull_taxa(x,is_from_gut), "brown", "lemonchiffon"),
     vertex.frame.color = colormap_comms$`mOTU-Functional`[comm_id(x)],
     vertex.frame.width = 2.5)
mtext("a", side = 3, line = -4, adj = 0.1, cex = 2) 
```

```{r}
gather_taxa(CPH_netw_filt) %>%
  mutate(type = case_when(
    genus == "Pseudomonas" ~ "Pseudomonas",
    is_from_gut ~ "Human Gut",
    source == "amr" ~ "AMR",
    TRUE ~ "Other"
  )) %>%
  group_by(comm_id, type, mgnet) %>%
  summarise(count = n(), .groups = 'drop') %>%
  mutate(comm_id = factor(comm_id, levels = 1:17),
         mgnet = factor(mgnet, levels = c("mOTU-ResFinder", "mOTU-Functional"))) %>%
  ggplot(aes(x = comm_id, y = count, fill = type)) +
  geom_bar(stat = "identity") +
  facet_wrap(~mgnet, scales = "free_x") +
  theme_bw() +
  theme(legend.position = "top",
        axis.title = element_blank()) 
  
```


